config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "users/sign_up"
  get "users/sign_in"
  resources :users
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	# validates_uniquess_of :email
	# validates :email, uniqueness: true, precense: true
	validates_uniqueness_of :email
	validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def sign_up
		@user = User.new
	end

	def create
		puts params
		@user = User.new(user_params)

		if @user.save
			redirect_to root_path
		else
			render :sign_up
		end
	end

	def sign_in
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoSignUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/sign_up.html.erb
<div class="container sign-up">
	<div class="row">
		<div class="title">
			<h4>Sign Up Form</h4>
		</div>
	</div>
	<div class="row">
		<% if @user.errors.any? %>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		<% end %>
		<div class="sign-up-form col-md-4 col-md-offset-4">
			<%= form_for @user, class: "form-horizontal" do |f| %>
				<div class="form-group">
					<label class="control-label">First name</label>
					<%= f.text_field :first_name, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Last name</label>
					<%= f.text_field :last_name, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Email</label>
					<%= f.text_field :email, class: "form-control" %>
				</div>
				<div class="action">
					<%= f.submit class: "btn btn-primary" %>
					<label>
						<%= link_to "Sign In", users_sign_in_path, class: "btn btn-link" %>
					</label>
				</div>
			<% end %>
		</div>
	</div>
</div>